name: driver
description: "A new Flutter project (Frontend Only)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  country_code_picker: ^3.0.0
  crypto: ^3.0.5

  dotted_border: ^2.1.0
  geocoding: ^3.0.0

  cached_network_image: ^3.4.1
  flutter_easyloading: ^3.0.5
  flutter_email_sender: ^6.0.3
  flutter_html: any
  flutter_local_notifications: ^17.2.3
  flutter_svg: ^2.0.10+1
  geolocator: any
  location: ^6.0.2
  get: ^4.6.6
  google_maps_flutter: ^2.9.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  pin_code_fields: ^8.0.1

  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.3.2
  syncfusion_flutter_datepicker: ^27.1.53
  timer_count_down: ^2.2.2
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  date_picker_timeline: ^1.2.6
  flutter_rating_bar: ^4.0.1
  flutter_polyline_points: ^2.1.0
  clipboard: ^0.1.3
  map_launcher: ^3.5.0
  timelines_plus: ^1.0.3
  in_app_review: ^2.0.9
  share_plus: ^10.0.0
  mailer: ^6.2.0
  photo_view: ^0.15.0
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.4
  path: ^1.9.0
  video_compress: ^3.1.3
  video_player: ^2.9.2
  audioplayers: ^6.0.0

  osm_nominatim: ^3.0.1
  flutter_osm_plugin: ^1.3.3+1

  http: any
  webview_flutter: any

dependency_overrides:
  webview_flutter: ^4.10.0
  http: ^1.2.2
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Urbanist-Black
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
    - family: Urbanist-Bold
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
    - family: Urbanist-ExtraBold
      fonts:
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
    - family: Urbanist-ExtraLight
      fonts:
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
    - family: Urbanist-Light
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf
    - family: Urbanist-Medium
      fonts:
        - asset: assets/fonts/Urbanist-Medium.ttf
    - family: Urbanist-Regular
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
    - family: Urbanist-SemiBold
      fonts:
        - asset: assets/fonts/Urbanist-SemiBold.ttf
    - family: Urbanist-Thin
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/audio/
    - assets/
