name: restaurant
description: "A new Flutter project (Frontend Only)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  country_code_picker: ^3.0.0
  crypto: ^3.0.5

  dotted_border: ^2.1.0
  geocoding: ^3.0.0

  cached_network_image: ^3.3.1
  flutter_easyloading: ^3.0.5
  flutter_email_sender: ^6.0.3
  flutter_html: any
  flutter_local_notifications: ^17.2.2
  flutter_svg: ^2.0.10+1
  geolocator: any
  location: ^6.0.2
  get: ^4.6.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  pin_code_fields: ^8.0.1

  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.3.2
  syncfusion_flutter_datepicker: ^26.2.14
  timer_count_down: ^2.2.2
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  date_picker_timeline: ^1.2.6
  flutter_rating_bar: ^4.0.1
  datetime_picker_formfield_new: ^2.1.0
  flutter_polyline_points: ^2.1.0
  clipboard: ^0.1.3
  map_launcher: ^3.4.0
  story_view: ^0.16.5
  bottom_picker: ^2.8.0
  multi_select_flutter: ^4.1.3
  in_app_review: ^2.0.9
  share_plus: ^10.0.0
  photo_view: ^0.15.0
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.4
  video_compress: ^3.1.3
  flutter_video_info: ^1.3.2
  mime: ^1.0.6
  mailer: ^6.1.2
  dropdown_search: ^5.0.6
  flutter_multi_formatter: ^2.13.0
  audioplayers: ^6.1.0
  image_gallery_saver_plus: ^3.0.5

  osm_nominatim: ^3.0.1
  flutter_osm_plugin: ^1.2.0

  video_player: any
  google_maps_flutter: any
  google_maps_place_picker_mb: any
  http: any

  esc_pos_utils: any
  print_bluetooth_thermal: ^1.1.1

dependency_overrides:
  webview_flutter: ^4.8.0
  http: ^1.2.2
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Urbanist-Black
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
    - family: Urbanist-Bold
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
    - family: Urbanist-ExtraBold
      fonts:
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
    - family: Urbanist-ExtraLight
      fonts:
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
    - family: Urbanist-Light
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf
    - family: Urbanist-Medium
      fonts:
        - asset: assets/fonts/Urbanist-Medium.ttf
    - family: Urbanist-Regular
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
    - family: Urbanist-SemiBold
      fonts:
        - asset: assets/fonts/Urbanist-SemiBold.ttf
    - family: Urbanist-Thin
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/
